<?php defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * CodeIgniter Autocomplete Helper
 *
 * Este archivo es para autocompletar los modelos en CodeIgniter.
 */

// Lista de todos los modelos utilizados en la aplicación
/**
 * @property AC_Activities_model $AC_Activities_model
 * @property AC_Beneficiaries_model $AC_Beneficiaries_model
 * @property AC_Client_agreements_info_model $AC_Client_agreements_info_model
 * @property AC_Communes_model $AC_Communes_model
 * @property AC_Configuration_annual_program_files_model $AC_Configuration_annual_program_files_model
 * @property AC_Configuration_associated_payments_model $AC_Configuration_associated_payments_model
 * @property AC_Configuration_model $AC_Configuration_model
 * @property AC_Execution_records_files_model $AC_Execution_records_files_model
 * @property AC_Execution_records_model $AC_Execution_records_model
 * @property AC_Feeders_activity_objectives_model $AC_Feeders_activity_objectives_model
 * @property AC_Feeders_beneficiary_objectives_model $AC_Feeders_beneficiary_objectives_model
 * @property AC_Feeders_centrals_model $AC_Feeders_centrals_model
 * @property AC_Feeders_societies_model $AC_Feeders_societies_model
 * @property AC_Feeders_type_of_activities_model $AC_Feeders_type_of_activities_model
 * @property AC_Feeders_types_agreements_model $AC_Feeders_types_agreements_model
 * @property AC_Information_audits_model $AC_Information_audits_model
 * @property AC_Information_closing_files_model $AC_Information_closing_files_model
 * @property AC_Information_closing_model $AC_Information_closing_model
 * @property AC_Information_model $AC_Information_model
 * @property AC_Macrozones_model $AC_Macrozones_model
 * @property AC_Types_of_activities_model $AC_Types_of_activities_model
 * @property Activity_logs_model $Activity_logs_model
 * @property Agreements_evidences_model $Agreements_evidences_model
 * @property Agreements_matrix_config_model $Agreements_matrix_config_model
 * @property Agreements_monitoring_model $Agreements_monitoring_model
 * @property Agreements_rel_fields_model $Agreements_rel_fields_model
 * @property Announcements_model $Announcements_model
 * @property Api_model $Api_model
 * @property Assignment_combinations_model $Assignment_combinations_model
 * @property Assignment_model $Assignment_model
 * @property Attendance_model $Attendance_model
 * @property AYN_Admin_modules_model $AYN_Admin_modules_model
 * @property AYN_Admin_submodules_model $AYN_Admin_submodules_model
 * @property AYN_Alert_historical_model $AYN_Alert_historical_model
 * @property AYN_Alert_historical_users_model $AYN_Alert_historical_users_model
 * @property AYN_Alert_projects_groups_model $AYN_Alert_projects_groups_model
 * @property AYN_Alert_projects_model $AYN_Alert_projects_model
 * @property AYN_Alert_projects_users_model $AYN_Alert_projects_users_model
 * @property AYN_Clients_groups_model $AYN_Clients_groups_model
 * @property AYN_Notif_general_groups_model $AYN_Notif_general_groups_model
 * @property AYN_Notif_general_model $AYN_Notif_general_model
 * @property AYN_Notif_general_users_model $AYN_Notif_general_users_model
 * @property AYN_Notif_historical_model $AYN_Notif_historical_model
 * @property AYN_Notif_historical_users_model $AYN_Notif_historical_users_model
 * @property AYN_Notif_projects_admin_groups_model $AYN_Notif_projects_admin_groups_model
 * @property AYN_Notif_projects_admin_model $AYN_Notif_projects_admin_model
 * @property AYN_Notif_projects_admin_users_model $AYN_Notif_projects_admin_users_model
 * @property AYN_Notif_projects_clients_groups_model $AYN_Notif_projects_clients_groups_model
 * @property AYN_Notif_projects_clients_model $AYN_Notif_projects_clients_model
 * @property AYN_Notif_projects_clients_users_model $AYN_Notif_projects_clients_users_model
 * @property Calculation_model $Calculation_model
 * @property Categories_alias_model $Categories_alias_model
 * @property Categories_model $Categories_model
 * @property Characterization_factors_model $Characterization_factors_model
 * @property Client_compromises_settings_model $Client_compromises_settings_model
 * @property Client_consumptions_settings_model $Client_consumptions_settings_model
 * @property Client_context_modules_model $Client_context_modules_model
 * @property Client_context_modules_rel_profiles_model $Client_context_modules_rel_profiles_model
 * @property Client_context_profiles_model $Client_context_profiles_model
 * @property Client_context_submodules_model $Client_context_submodules_model
 * @property Client_environmental_footprints_settings_model $Client_environmental_footprints_settings_model
 * @property Client_indicators_model $Client_indicators_model
 * @property Client_module_availability_model $Client_module_availability_model
 * @property Client_permitting_settings_model $Client_permitting_settings_model
 * @property Client_waste_settings_model $Client_waste_settings_model
 * @property Clients_model $Clients_model
 * @property Clients_modules_model $Clients_modules_model
 * @property Clients_modules_rel_profiles_model $Clients_modules_rel_profiles_model
 * @property Clients_submodules_model $Clients_submodules_model
 * @property Communities_evaluation_status_model $Communities_evaluation_status_model
 * @property Communities_providers_model $Communities_providers_model
 * @property Compromises_compliance_evaluation_rca_model $Compromises_compliance_evaluation_rca_model
 * @property Compromises_compliance_evaluation_reportables_model $Compromises_compliance_evaluation_reportables_model
 * @property Compromises_compliance_evidences_model $Compromises_compliance_evidences_model
 * @property Compromises_compliance_status_model $Compromises_compliance_status_model
 * @property Compromises_rca_model $Compromises_rca_model
 * @property Compromises_rca_rel_fields_model $Compromises_rca_rel_fields_model
 * @property Compromises_reportables_model $Compromises_reportables_model
 * @property Compromises_reportables_rel_fields_model $Compromises_reportables_rel_fields_model
 * @property Contact_model $Contact_model
 * @property Contingencies_correction_record_model $Contingencies_correction_record_model
 * @property Contingencies_event_record_model $Contingencies_event_record_model
 * @property Contingencies_verification_record_model $Contingencies_verification_record_model
 * @property Conversion_model $Conversion_model
 * @property Countries_model $Countries_model
 * @property Critical_levels_model $Critical_levels_model
 * @property Crud_bd_fc_model $Crud_bd_fc_model
 * @property Crud_model $Crud_model
 * @property Custom_field_values_model $Custom_field_values_model
 * @property Custom_fields_model $Custom_fields_model
 * @property Databases_model $Databases_model
 * @property EC_Client_transformation_factors_config_model $EC_Client_transformation_factors_config_model
 * @property EC_Types_no_apply_model $EC_Types_no_apply_model
 * @property EC_Types_of_origin_matter_model $EC_Types_of_origin_matter_model
 * @property EC_Types_of_origin_model $EC_Types_of_origin_model
 * @property Email_templates_model $Email_templates_model
 * @property Environmental_records_model $Environmental_records_model
 * @property Estimate_forms_model $Estimate_forms_model
 * @property Estimate_items_model $Estimate_items_model
 * @property Estimate_requests_model $Estimate_requests_model
 * @property Estimates_model $Estimates_model
 * @property Evaluated_permitting_model $Evaluated_permitting_model
 * @property Evaluated_rca_compromises_model $Evaluated_rca_compromises_model
 * @property Events_model $Events_model
 * @property Expense_categories_model $Expense_categories_model
 * @property Expenses_model $Expenses_model
 * @property Faq_model $Faq_model
 * @property Feedback_matrix_config_model $Feedback_matrix_config_model
 * @property Feedback_monitoring_evidences_model $Feedback_monitoring_evidences_model
 * @property Feedback_monitoring_model $Feedback_monitoring_model
 * @property Feedback_rel_fields_model $Feedback_rel_fields_model
 * @property Feeders_model $Feeders_model
 * @property FH_rel_methodology_model $FH_rel_methodology_model
 * @property Field_rel_form_model $Field_rel_form_model
 * @property Field_types_model $Field_types_model
 * @property Fields_model $Fields_model
 * @property Fixed_feeder_management_model $Fixed_feeder_management_model
 * @property Fixed_feeder_treatment_sidrep_model $Fixed_feeder_treatment_sidrep_model
 * @property Fixed_feeder_treatment_sinader_model $Fixed_feeder_treatment_sinader_model
 * @property Fixed_feeder_waste_receiving_companies_values_model $Fixed_feeder_waste_receiving_companies_values_model
 * @property Fixed_feeder_waste_transport_companies_values_model $Fixed_feeder_waste_transport_companies_values_model
 * @property Fixed_field_rel_form_rel_project_model $Fixed_field_rel_form_rel_project_model
 * @property Fixed_fields_model $Fixed_fields_model
 * @property Fixed_form_values_model $Fixed_form_values_model
 * @property Fontawesome_model $Fontawesome_model
 * @property Footprint_format_model $Footprint_format_model
 * @property Footprints_model $Footprints_model
 * @property Form_rel_material_model $Form_rel_material_model
 * @property Form_rel_materiales_rel_categorias_model $Form_rel_materiales_rel_categorias_model
 * @property Form_rel_project_model $Form_rel_project_model
 * @property Form_types_model $Form_types_model
 * @property Form_values_model $Form_values_model
 * @property Forms_model $Forms_model
 * @property Functional_units_model $Functional_units_model
 * @property General_files_model $General_files_model
 * @property General_settings_clients_model $General_settings_clients_model
 * @property General_settings_model $General_settings_model
 * @property Help_articles_model $Help_articles_model
 * @property Help_categories_model $Help_categories_model
 * @property Home_modules_info_model $Home_modules_info_model
 * @property Indicators_model $Indicators_model
 * @property Industries_model $Industries_model
 * @property Industries_rel_technologies_model $Industries_rel_technologies_model
 * @property Invoice_items_model $Invoice_items_model
 * @property Invoice_payments_model $Invoice_payments_model
 * @property Invoices_model $Invoices_model
 * @property Items_model $Items_model
 * @property KPI_Charts_structure_model $KPI_Charts_structure_model
 * @property KPI_Report_structure_model $KPI_Report_structure_model
 * @property KPI_Report_templates_model $KPI_Report_templates_model
 * @property KPI_Values_condition_model $KPI_Values_condition_model
 * @property KPI_Values_model $KPI_Values_model
 * @property Leave_applications_model $Leave_applications_model
 * @property Leave_types_model $Leave_types_model
 * @property Materials_model $Materials_model
 * @property Materials_rel_category_model $Materials_rel_category_model
 * @property Messages_model $Messages_model
 * @property Methodology_model $Methodology_model
 * @property Methodology_rel_footprints_model $Methodology_rel_footprints_model
 * @property Milestones_model $Milestones_model
 * @property Mimasoft_model $Mimasoft_model
 * @property Module_availability_model $Module_availability_model
 * @property Module_footprint_units_model $Module_footprint_units_model
 * @property Nisira_categories_by_groups_model $Nisira_categories_by_groups_model
 * @property Nisira_or_uf_by_groups_model $Nisira_or_uf_by_groups_model
 * @property Nisira_projects_by_idconsumidor_model $Nisira_projects_by_idconsumidor_model
 * @property Nisira_projects_by_sucursal_model $Nisira_projects_by_sucursal_model
 * @property Nisira_uploaded_data_log_model $Nisira_uploaded_data_log_model
 * @property Notes_model $Notes_model
 * @property Notification_settings_model $Notification_settings_model
 * @property Notifications_model $Notifications_model
 * @property Other_records_model $Other_records_model
 * @property Patents_model $Patents_model
 * @property Payment_methods_model $Payment_methods_model
 * @property Paypal_ipn_model $Paypal_ipn_model
 * @property Permitting_model $Permitting_model
 * @property Permitting_procedure_evaluation_model $Permitting_procedure_evaluation_model
 * @property Permitting_procedure_evidences_model $Permitting_procedure_evidences_model
 * @property Permitting_procedure_status_model $Permitting_procedure_status_model
 * @property Permitting_rel_fields_model $Permitting_rel_fields_model
 * @property Phase_rel_pu_model $Phase_rel_pu_model
 * @property Phases_model $Phases_model
 * @property Plans_reportables_compromises_model $Plans_reportables_compromises_model
 * @property Posts_model $Posts_model
 * @property Profiles_model $Profiles_model
 * @property Project_comments_model $Project_comments_model
 * @property Project_files_model $Project_files_model
 * @property Project_members_model $Project_members_model
 * @property Project_rel_activities_model $Project_rel_activities_model
 * @property Project_rel_footprints_model $Project_rel_footprints_model
 * @property Project_rel_material_model $Project_rel_material_model
 * @property Project_rel_phases_model $Project_rel_phases_model
 * @property Project_rel_pu_model $Project_rel_pu_model
 * @property Project_settings_model $Project_settings_model
 * @property Projects_model $Projects_model
 * @property Reports_configuration_model $Reports_configuration_model
 * @property Reports_model $Reports_model
 * @property Reports_units_settings_clients_model $Reports_units_settings_clients_model
 * @property Reports_units_settings_model $Reports_units_settings_model
 * @property Roles_model $Roles_model
 * @property Rule_model $Rule_model
 * @property Settings_model $Settings_model
 * @property Sidrep_codes_model $Sidrep_codes_model
 * @property Sinader_code_model $Sinader_code_model
 * @property Social_links_model $Social_links_model
 * @property Stakeholders_matrix_config_model $Stakeholders_matrix_config_model
 * @property Stakeholders_rel_fields_model $Stakeholders_rel_fields_model
 * @property Subcategories_model $Subcategories_model
 * @property Subcategory_rel_categories_model $Subcategory_rel_categories_model
 * @property Subindustries_model $Subindustries_model
 * @property Subprojects_model $Subprojects_model
 * @property Tasks_model $Tasks_model
 * @property Taxes_model $Taxes_model
 * @property Team_model $Team_model
 * @property Technologies_model $Technologies_model
 * @property Thresholds_model $Thresholds_model
 * @property Ticket_comments_model $Ticket_comments_model
 * @property Ticket_types_model $Ticket_types_model
 * @property Tickets_model $Tickets_model
 * @property Timesheets_model $Timesheets_model
 * @property Tipo_tratamiento_model $Tipo_tratamiento_model
 * @property Todo_model $Todo_model
 * @property Types_of_organization_model $Types_of_organization_model
 * @property Unit_processes_model $Unit_processes_model
 * @property Unity_model $Unity_model
 * @property Unity_type_model $Unity_type_model
 * @property Users_model $Users_model
 * @property Values_agreements_model $Values_agreements_model
 * @property Values_compromises_rca_model $Values_compromises_rca_model
 * @property Values_compromises_reportables_model $Values_compromises_reportables_model
 * @property Values_feedback_model $Values_feedback_model
 * @property Values_model $Values_model
 * @property Values_permitting_model $Values_permitting_model
 * @property Values_stakeholders_model $Values_stakeholders_model
 * @property Wiki_model $Wiki_model
 * @property CI_Input $input
 * @property CI_Session $session
 * @property Template $template
 */
class CI_Controller {};

